blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/phakhawatchu/libthai-idcard/discussions
    about: Ask questions and discuss ideas
  - name: Documentation
    url: https://docs.rs/libthai-idcard
    about: Read the API documentation
